#ifndef PRIORITYGENERATOR_GLOBAL_H
#define PRIORITYGENERATOR_GLOBAL_H

#include "../SoCINGlobal.h"

#if defined(PRIORITYGENERATOR_LIBRARY)
#  define PG_SHARED_EXPORT SS_DECL_EXPORT
#else
#  define PG_SHARED_EXPORT SS_DECL_IMPORT
#endif

#endif // PRIORITYGENERATOR_GLOBAL_H
